namespace :load_default_data do
  desc "create all health ensurances used"
  task health_ensurances: :environment do
    HealthEnsurance.create([
      { name: 'BRADESCO' },
      { name: 'HOSPITAL PEQUENO PRINCIPE' },
      { name: 'INSTITUTO PELÉ PEQUENO PRÍNCIPE' },
      { name: 'SESMT' },
      { name: 'LABORATORIO EXAMINARE - STA BRÍGIDA' },
      { name: 'ALLIANZ SAUDE' },
      { name: 'AMIL' },
      { name: 'AMIL DIX CLASSIC' },
      { name: 'BANCO DO BRASIL CASSI' },
      { name: 'CAIXA ECONOMICA FEDERAL' },
      { name: 'CARE PLUS' },
      { name: 'CENTAURO SEGURADORA' },
      { name: 'CLINICA ADVENTISTA DE CURITIBA' },
      { name: 'CLINIPAM' },
      { name: 'COAMO - FUPS' },
      { name: 'COLEGIO BOM JESUS' },
      { name: 'COPEL' },
      { name: 'CORITIBA FOOT BALL CLUB' },
      { name: 'C.S ASSISTANCE' },
      { name: 'ELETROSUL' },
      { name: 'ESTADO DO MATO GROSSO' },
      { name: 'FASSINCRA' },
      { name: 'FUNDACAO SANEPAR' },
      { name: 'FUNDACAO SAUDE ITAU' },
      { name: 'FUNDO DO ESTADO DE CANOINHAS' },
      { name: 'FUNDO EST DE SAUDE DO PR FUNSA' },
      { name: 'FUNDO EST DE SAUDE MATO GROSSO' },
      { name: 'FUNDO EST DE SAUDE P. EST PARA' },
      { name: 'FUNDO EST DE SAUDE RONDONIA' },
      { name: 'FUNDO EST DE SAUDE FLORIANOPOLIS' },
      { name: 'FUNDO MUNI DE SAUDE DE IBIRAMA' },
      { name: 'FUNSEP' },
      { name: 'FUSEX' },
      { name: 'GAMA SAUDE' },
      { name: 'GEAP' },
      { name: 'GMC DO BRASIL' },
      { name: 'ICS' },
      { name: 'IMASP - INST.MUNIC. DE ASSIST' },
      { name: 'ITAIPU BINACIONAL' },
      { name: 'MEDISERVICE' },
      { name: 'NOSSA SAUDE' },
      { name: 'NOTRE DAME' },
      { name: 'PARANA CLINICAS' },
      { name: 'PARTICULAR' },
      { name: 'PESQUISA CLINICA LABORAT. HPP' },
      { name: 'PETROBRAS DISTRIBUIDORA - BR' },
      { name: 'PETROBRAS PETROLEO' },
      { name: 'PLASSMA' },
      { name: 'PRO SAUDE UEPG' },
      { name: 'PROASA' },
      { name: 'SANTA CASA DE MARINGA' },
      { name: 'SAUDE IDEAL' },
      { name: 'SECRETARIA MUNICIPAL DE SAUDE' },
      { name: 'SINDESTIVA' },
      { name: 'SUL AMERICA SAUDE' },
      { name: 'SUS - AMBULATÓRIO' },
      { name: 'SUS - INTERNAÇÃO' },
      { name: 'TEMPO SAUDE' },
      { name: 'UNIMED CURITIBA' },
      { name: 'UNIMED INTERCAMBIO' },
      { name: 'VACINI' },
      { name: 'VOLVO DO BRASIL - VOAM' },
      { name: 'WAL-MART BRASIL' },
      { name: 'VOLKSWAGEN' },
      { name: 'HOSPITAL ERASTO GAERTNER' },
      { name: 'CINDACTA' },
      { name: 'HNSG' },
      { name: 'PORTARIA GM/MS 199' },
      { name: 'UOPECCAN' },
    ])
  end

  desc "TODO"
  task offered_exams: :environment do
  end

end
