namespace :update_model_db do
  desc "Task gerada para atualizar os registros referentes aos exames oferecidos."
  task offered_exam: :environment do
    puts "Atualizando OfferedExams ..."

    #IMUNOFENO
    OfferedExam.find_by({name: 'IMUNOFENOTIPAGEM DE NEOPLASIAS HEMATOLÓGICAS'}).update(refference_date: 5)
    OfferedExam.find_by({name: 'IMUNOFENOTIPAGEM DE NEOPLASIAS HEMATOLÓGICAS'}).update(refference_date: 5)
    OfferedExam.find_by({name: 'IMUNOFENOTIPAGEM DE LINFÓCITOS NK (CD3-/CD16+/CD56+)'}).update(refference_date: 5)
    OfferedExam.find_by({name: 'IMUNOFENOTIPAGEM DE LINFÓCITOS B (CD19+)'}).update(refference_date: 5)
    OfferedExam.find_by({name: 'IMUNOFENOTIPAGEM DE LINFÓCITOS T - TOTAL (CD3+)'}).update(refference_date: 5)
    OfferedExam.find_by({name: 'IMUNOFENOTIPAGEM DE LINFÓCITOS T HELPER (CD3+/CD4+)'}).update(refference_date: 5)
    OfferedExam.find_by({name: 'IMUNOFENOTIPAGEM DE LINFÓCITOS CD4/CD8'}).update(refference_date: 5)
    OfferedExam.find_by({name: 'IMUNOFENOTIPAGEM DE LINFÓCITOS CD20+'}).update(refference_date: 5)
    OfferedExam.find_by({name: 'IMUNOFENOTIPAGEM DE LINFÓCITOS CD2+'}).update(refference_date: 5)
    OfferedExam.find_by({name: 'IMUNOFENOTIPAGEM DE LINFÓCITOS T  (CD3+) E B (CD19+)'}).update(refference_date: 5)
    OfferedExam.find_by({name: 'IMUNOFENOTIPAGEM  PÓS TMO RECUPERAÇÃO IMUNE'}).update(refference_date: 5)
    OfferedExam.find_by({name: 'MARCADOR CD1a'}).update(refference_date: 5)
    OfferedExam.find_by({name: 'MARCADOR CD2'}).update(refference_date: 5)
    OfferedExam.find_by({name: 'MARCADOR CD3'}).update(refference_date: 5)
    OfferedExam.find_by({name: 'MARCADOR CD3 CITOPLASMA'}).update(refference_date: 5)
    OfferedExam.find_by({name: 'MARCADOR CD4'}).update(refference_date: 5)
    OfferedExam.find_by({name: 'MARCADOR CD5'}).update(refference_date: 5)
    OfferedExam.find_by({name: 'MARCADOR CD7'}).update(refference_date: 5)
    OfferedExam.find_by({name: 'MARCADOR CD8'}).update(refference_date: 5)
    OfferedExam.find_by({name: 'MARCADOR CD9'}).update(refference_date: 5)
    OfferedExam.find_by({name: 'MARCADOR CD10'}).update(refference_date: 5)
    OfferedExam.find_by({name: 'MARCADOR CD11b'}).update(refference_date: 5)
    OfferedExam.find_by({name: 'MARCADOR CD13'}).update(refference_date: 5)
    OfferedExam.find_by({name: 'MARCADOR CD14'}).update(refference_date: 5)
    OfferedExam.find_by({name: 'MARCADOR CD15'}).update(refference_date: 5)
    OfferedExam.find_by({name: 'MARCADOR CD16'}).update(refference_date: 5)
    OfferedExam.find_by({name: 'MARCADOR CD19'}).update(refference_date: 5)
    OfferedExam.find_by({name: 'MARCADOR CD20'}).update(refference_date: 5)
    OfferedExam.find_by({name: 'MARCADOR CD21'}).update(refference_date: 5)
    OfferedExam.find_by({name: 'MARCADOR CD22'}).update(refference_date: 5)
    OfferedExam.find_by({name: 'MARCADOR CD33'}).update(refference_date: 5)
    OfferedExam.find_by({name: 'MARCADOR CD34'}).update(refference_date: 5)
    OfferedExam.find_by({name: 'MARCADOR CD35'}).update(refference_date: 5)
    OfferedExam.find_by({name: 'MARCADOR CD36'}).update(refference_date: 5)
    OfferedExam.find_by({name: 'MARCADOR CD38'}).update(refference_date: 5)
    OfferedExam.find_by({name: 'MARCADOR CD45'}).update(refference_date: 5)
    OfferedExam.find_by({name: 'MARCADOR CD45RA'}).update(refference_date: 5)
    OfferedExam.find_by({name: 'MARCADOR CD45RO'}).update(refference_date: 5)
    OfferedExam.find_by({name: 'MARCADOR CD56'}).update(refference_date: 5)
    OfferedExam.find_by({name: 'MARCADOR CD58'}).update(refference_date: 5)
    OfferedExam.find_by({name: 'MARCADOR CD64'}).update(refference_date: 5)
    OfferedExam.find_by({name: 'MARCADOR CD66c'}).update(refference_date: 5)
    OfferedExam.find_by({name: 'MARCADOR CD71'}).update(refference_date: 5)
    OfferedExam.find_by({name: 'MARCADOR CD79a CITOPLASMA'}).update(refference_date: 5)
    OfferedExam.find_by({name: 'MARCADOR CD81'}).update(refference_date: 5)
    OfferedExam.find_by({name: 'MARCADOR CD99'}).update(refference_date: 5)
    OfferedExam.find_by({name: 'MARCADOR CD117'}).update(refference_date: 5)
    OfferedExam.find_by({name: 'MARCADOR CD123'}).update(refference_date: 5)
    OfferedExam.find_by({name: 'MARCADOR HLA-DR'}).update(refference_date: 5)
    OfferedExam.find_by({name: 'MARCADOR IGM'}).update(refference_date: 5)
    OfferedExam.find_by({name: 'MARCADOR IGM CITOPLASMA'}).update(refference_date: 5)
    OfferedExam.find_by({name: 'MARCADOR IREM2'}).update(refference_date: 5)
    OfferedExam.find_by({name: 'MARCADOR KAPPA'}).update(refference_date: 5)
    OfferedExam.find_by({name: 'MARCADOR KAPPA CITOPLASMA'}).update(refference_date: 5)
    OfferedExam.find_by({name: 'MARCADOR LAMBDA'}).update(refference_date: 5)
    OfferedExam.find_by({name: 'MARCADOR LAMBDA CITOPLASMA'}).update(refference_date: 5)
    OfferedExam.find_by({name: 'MARCADOR MPO CITOPLASMA'}).update(refference_date: 5)
    OfferedExam.find_by({name: 'MARCADOR NG2'}).update(refference_date: 5)
    OfferedExam.find_by({name: 'MARCADOR TCRAB'}).update(refference_date: 5)
    OfferedExam.find_by({name: 'MARCADOR TCRGD'}).update(refference_date: 5)
    OfferedExam.find_by({name: 'MARCADOR TDT NUCLEAR'}).update(refference_date: 5)
    OfferedExam.find_by({name: 'MARCADOR 7AAD (VIABILIDADE)'}).update(refference_date: 5)

    #ANATOMIA
    OfferedExam.find_by({name: 'ANÁTOMO PATOLÓGICO ONCO'}).update(refference_date: 10)
    OfferedExam.find_by({name: 'IMUNOHISTOQUÍMICA ONCO'}).update(refference_date: 15)

    # #FISH
    OfferedExam.find_by({name: 'PAINEL DE ALTERAÇÕES CROMOSSÔMICAS EM LLA POR FISH'}).update(refference_date: 20)
    OfferedExam.find_by({name: 'PESQUISA DA FUSÃO BCR-ABL1 POR FISH'}).update(refference_date: 20)
    OfferedExam.find_by({name: 'PESQUISA DA QUEBRA DO GENE KMT2A (MLL) POR FISH'}).update(refference_date: 20)
    OfferedExam.find_by({name: 'PESQUISA DA FUSÃO ETV6-RUNX1 (TEL-AML1) POR FISH'}).update(refference_date: 20)
    OfferedExam.find_by({name: 'PESQUISA DA QUEBRA DO GENE CBFB POR FISH'}).update(refference_date: 20)
    OfferedExam.find_by({name: 'PESQUISA DA FUSÃO PML-RARA POR FISH'}).update(refference_date: 20)
    OfferedExam.find_by({name: 'PESQUISA DA FUSÃO RUNX1/RUNX1T1 (AML1-ETO) POR FISH'}).update(refference_date: 20)
    OfferedExam.find_by({name: 'PESQUISA DE ALTERAÇÃO NUMÉRICA DO CROMOSSOMO 4 POR FISH'}).update(refference_date: 20)
    OfferedExam.find_by({name: 'PESQUISA DE ALTERAÇÃO NUMÉRICA DO CROMOSSOMO 10 POR FISH'}).update(refference_date: 20)
    OfferedExam.find_by({name: 'PESQUISA DE ALTERAÇÃO NUMÉRICA DO CROMOSSOMO 17 POR FISH'}).update(refference_date: 20)
    OfferedExam.find_by({name: 'PESQUISA DA AMPLIFICAÇÃO DO GENE N-MYC POR FISH (NEUROBLASTOMA)'}).update(refference_date: 30)
    OfferedExam.find_by({name: 'PESQUISA DA DELEÇÃO 1P POR FISH'}).update(refference_date: 20)
    OfferedExam.find_by({name: 'PESQUISA DA DELEÇÃO 19Q POR FISH'}).update(refference_date: 20)
    OfferedExam.find_by({name: 'PAINEL DE ALTERAÇÕES CROMOSSÔMICAS EM LMA POR FISH'}).update(refference_date: 20)

    # #BIOMOL
    OfferedExam.find_by({name: 'PESQUISA DO REARRANJO BCR-ABL1 (P190) POR PCR'}).update(refference_date: 12)
    OfferedExam.find_by({name: 'QUANTIFICAÇÃO DO REARRANJO BCR-ABL1 P190 POR PCR EM TEMPO REAL'}).update(refference_date: 12)
    OfferedExam.find_by({name: 'QUANTIFICAÇÃO DO REARRANJO BCR-ABL1 P210 POR PCR EM TEMPO REAL'}).update(refference_date: 12)
    OfferedExam.find_by({name: 'QUANTIFICAÇÃO DO REARRANJO PML-RARA BCR1 POR PCR EM TEMPO REAL'}).update(refference_date: 12)
    OfferedExam.find_by({name: 'QUANTIFICAÇÃO DO REARRANJO PML-RARA BCR2 POR PCR EM TEMPO REAL'}).update(refference_date: 12)
    OfferedExam.find_by({name: 'QUANTIFICAÇÃO DO REARRANJO PML-RARA BCR3 POR PCR EM TEMPO REAL'}).update(refference_date: 12)
    OfferedExam.find_by({name: 'EXOMA ONCOLOGIA'}).update(refference_date: 90)
    OfferedExam.find_by({name: 'SEQUENCIAMENTO SANGER GENE FLT3 - PESQUISA DA MUTAÇÃO D835'}).update(refference_date: 20)
    OfferedExam.find_by({name: 'SEQUENCIAMENTO SANGER GENE FLT3 - ITD'}).update(refference_date: 20)
    OfferedExam.find_by({name: 'SEQUENCIAMENTO SANGER GENE NPM1 - INDEL'}).update(refference_date: 20)
    OfferedExam.find_by({name: 'SEQUENCIAMENTO SANGER GENE CEBPA'}).update(refference_date: 20)
    OfferedExam.find_by({name: 'SEQUENCIAMENTO SANGER REARRANJO BCR-ABL1 - PESQUISA DE MUTAÇÃO TKD'}).update(refference_date: 20)
    OfferedExam.find_by({name: 'PAINEL DE ALTERAÇÕES EM LLA POR PCR'}).update(refference_date: 12)
    OfferedExam.find_by({name: 'PESQUISA DO REARRANJO BCR-ABL1 P210 POR PCR'}).update(refference_date: 12)
    OfferedExam.find_by({name: 'PESQUISA DO REARRANJO ETV6-RUNX1 (TEL-AML1) POR PCR'}).update(refference_date: 12)
    OfferedExam.find_by({name: 'PESQUISA DO REARRANJO KMT2A/AFF1 (MLL-AF4) POR PCR'}).update(refference_date: 12)
    OfferedExam.find_by({name: 'PESQUISA DO REARRANJO TCF3-PBX1 (E2A-PBX1) POR PCR'}).update(refference_date: 12)
    OfferedExam.find_by({name: 'PAINEL DE ALTERAÇÕES EM LMA POR PCR'}).update(refference_date: 12)
    OfferedExam.find_by({name: 'PESQUISA DO REARRANJO PML-RARA POR PCR'}).update(refference_date: 12)
    OfferedExam.find_by({name: 'PESQUISA DO REARRANJO RUNX1/RUNX1T1 (AML1-ETO) POR PCR'}).update(refference_date: 12)
    OfferedExam.find_by({name: 'PESQUISA DO REARRANJO CBFB-MYH11 POR PCR'}).update(refference_date: 12)
    OfferedExam.find_by({name: 'PESQUISA DO REARRANJO SIL-TAL1 POR PCR'}).update(refference_date: 12)
    OfferedExam.find_by({name: 'QUANTIFICAÇÃO DO CITOMEGALOVÍRUS POR PCR EM TEMPO REAL'}).update(refference_date: 12)
    OfferedExam.find_by({name: 'PAINEL REARRANJOS LEUCEMIA POR NGS'}).update(refference_date: 20)
    OfferedExam.find_by({name: 'PAINEL DOENÇA RESIDUAL MÍNIMA POR NGS'}).update(refference_date: 20)
    OfferedExam.find_by({name: 'PAINEL DE NEOPLASIAS INFANTIS POR NGS'}).update(refference_date: 20)
    OfferedExam.find_by({name: 'SEQUENCIAMENTO SANGER GENE KIT - EXONS 8-11 E 17'}).update(refference_date: 20)
    OfferedExam.find_by({name: 'SEQUENCIAMENTO SANGER GENE KIT - PESQUISA DA MUTAÇÃO D816V'}).update(refference_date: 20)
    OfferedExam.find_by({name: 'SEQUENCIAMENTO SANGER GENE BRAF - PESQUISA DA MUTAÇÃO V600E'}).update(refference_date: 20)
    OfferedExam.find_by({name: 'TIPAGEM DO GENE HLA-A EM ALTA RESOLUÇÃO'}).update(refference_date: 20)
    OfferedExam.find_by({name: 'TIPAGEM DO GENE HLA-B EM ALTA RESOLUÇÃO'}).update(refference_date: 20)
    OfferedExam.find_by({name: 'TIPAGEM DO GENE HLA-C EM ALTA RESOLUÇÃO'}).update(refference_date: 20)
    OfferedExam.find_by({name: 'TIPAGEM DO GENE HLA-DRB1 EM ALTA RESOLUÇÃO'}).update(refference_date: 20)
    OfferedExam.find_by({name: 'TIPAGEM DO GENE HLA-DQB1 EM ALTA RESOLUÇÃO'}).update(refference_date: 20)
    OfferedExam.find_by({name: 'TIPAGEM DO GENE HLA-DPB1 EM ALTA RESOLUÇÃO'}).update(refference_date: 20)
    OfferedExam.find_by({name: 'TIPAGENS DE GENES HLA DE CLASSE 1 E 2 EM ALTA RESOLUÇÃO'}).update(refference_date: 20)
    OfferedExam.find_by({name: 'TIPAGEM DO GENE HLA-A EM MÉDIA RESOLUÇÃO'}).update(refference_date: 20)
    OfferedExam.find_by({name: 'TIPAGEM DO GENE HLA-B EM MÉDIA RESOLUÇÃO'}).update(refference_date: 20)
    OfferedExam.find_by({name: 'TIPAGEM DO GENE HLA-C EM MÉDIA RESOLUÇÃO'}).update(refference_date: 20)
    OfferedExam.find_by({name: 'TIPAGEM DO GENE HLA-DRB1 EM MÉDIA RESOLUÇÃO'}).update(refference_date: 20)
    OfferedExam.find_by({name: 'TIPAGEM DO GENE HLA-DQB1 EM MÉDIA RESOLUÇÃO'}).update(refference_date: 20)
    OfferedExam.find_by({name: 'TIPAGEM DO GENE HLA-DPB1 EM MÉDIA RESOLUÇÃO'}).update(refference_date: 20)
    OfferedExam.find_by({name: 'TIPAGENS DE GENES HLA DE CLASSE 1 E 2 EM MÉDIA RESOLUÇÃO'}).update(refference_date: 20)

    # #CITOGENETICA
    OfferedExam.find_by({name: 'CARIÓTIPO DE MEDULA ÓSSEA COM BANDEAMENTO G ONCO'}).update(refference_date: 20)
    OfferedExam.find_by({name: 'CARIÓTIPO DE SANGUE PERIFÉRICO PARA DIAGNÓSTICO DE NEOPLASIAS'}).update(refference_date: 30)

  end

end
