default: &default
  adapter: postgresql
  username: postgres
  password: '1234'
  encoding: unicode
  host: localhost
  port: 5432
  pool: 5

development:
  <<: *default
  database: genomico_development
  min_messages: WARNING

test:
  <<: *default
  database: genomico_test
