# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7e84a59b734f6729f6323142b7f6b1a782a425cb1ffea43413c668d09c0eeb271e236951cc1810bc02ee5816456cfab8d004b5094cea7a1736d997d29652a67e

test:
  secret_key_base: 4dff74d552c442ee3c9bc9e07e9bc0dcd69da91ae370c2170407797f5b29850d02e2a3f9d76d24503bda49889cab94329a0840310f1873fa9f9b5487eef7a9c3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
